// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6YKyubvchE5MUelWjWBfHDcwamykMDe4',
    appId: '1:774273384894:web:ebebae52c8eadc31a339ef',
    messagingSenderId: '774273384894',
    projectId: 'chat-classes-flutter',
    authDomain: 'chat-classes-flutter.firebaseapp.com',
    storageBucket: 'chat-classes-flutter.appspot.com',
    measurementId: 'G-SZV3KGXLP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5IN5Wh-s8cU77ncisvo1QM6smpnU9do',
    appId: '1:774273384894:android:39ce92af27040faea339ef',
    messagingSenderId: '774273384894',
    projectId: 'chat-classes-flutter',
    storageBucket: 'chat-classes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqRiRRkOr1sSrJZXfwEAwcXtGUsBUeL4',
    appId: '1:774273384894:ios:2337b4ca4394b153a339ef',
    messagingSenderId: '774273384894',
    projectId: 'chat-classes-flutter',
    storageBucket: 'chat-classes-flutter.appspot.com',
    iosClientId: '774273384894-hs4te0feda0mb6rc5mlej0mhge7e8269.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatclasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqRiRRkOr1sSrJZXfwEAwcXtGUsBUeL4',
    appId: '1:774273384894:ios:a2ecd3826735b07da339ef',
    messagingSenderId: '774273384894',
    projectId: 'chat-classes-flutter',
    storageBucket: 'chat-classes-flutter.appspot.com',
    iosClientId: '774273384894-37pf4dl4rhggdbkjqqr8uiqtp5ponte2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatclasses.RunnerTests',
  );
}
